import { z } from 'zod';
import { WeatherLinkSensorDataSchema } from './current.js';

const numOrNull = z.number().nullable().optional();

export const HistoricIssConditionsSchema = z.object({
  ts: z.number(),
  arch_int: numOrNull,
  temp_avg: numOrNull,
  temp_hi: numOrNull,
  temp_hi_at: numOrNull,
  temp_lo: numOrNull,
  temp_lo_at: numOrNull,
  hum_last: numOrNull,
  hum_hi: numOrNull,
  hum_hi_at: numOrNull,
  hum_lo: numOrNull,
  hum_lo_at: numOrNull,
  dew_point_last: numOrNull,
  dew_point_hi: numOrNull,
  dew_point_hi_at: numOrNull,
  dew_point_lo: numOrNull,
  dew_point_lo_at: numOrNull,
  wet_bulb_last: numOrNull,
  wet_bulb_hi: numOrNull,
  wet_bulb_hi_at: numOrNull,
  wet_bulb_lo: numOrNull,
  wet_bulb_lo_at: numOrNull,
  heat_index_last: numOrNull,
  heat_index_hi: numOrNull,
  heat_index_hi_at: numOrNull,
  wind_chill_last: numOrNull,
  wind_chill_lo: numOrNull,
  wind_chill_lo_at: numOrNull,
  thw_index_last: numOrNull,
  thw_index_hi: numOrNull,
  thw_index_hi_at: numOrNull,
  thsw_index_last: numOrNull,
  thsw_index_hi: numOrNull,
  thsw_index_hi_at: numOrNull,
  wind_speed_avg: numOrNull,
  wind_speed_hi: numOrNull,
  wind_speed_hi_at: numOrNull,
  wind_dir_of_hi: numOrNull,
  wind_dir_of_prevail: numOrNull,
  wind_run: numOrNull,
  wind_num_samples: numOrNull,
  rain_rate_hi_clicks: numOrNull,
  rain_rate_hi_in: numOrNull,
  rain_rate_hi_mm: numOrNull,
  rain_rate_hi_at: numOrNull,
  rainfall_clicks: numOrNull,
  rainfall_in: numOrNull,
  rainfall_mm: numOrNull,
  solar_rad_avg: numOrNull,
  solar_rad_hi: numOrNull,
  solar_rad_hi_at: numOrNull,
  uv_index_avg: numOrNull,
  uv_index_hi: numOrNull,
  uv_index_hi_at: numOrNull,
  uv_dose: numOrNull,
  solar_energy: numOrNull,
  et: numOrNull,
  deg_days_heat: numOrNull,
  deg_days_cool: numOrNull,
  tx_id: numOrNull,
  iss_reception: numOrNull,
}).passthrough();

export type HistoricIssConditions = z.infer<typeof HistoricIssConditionsSchema>;

export const WeatherLinkHistoricResponseSchema = z.object({
  station_id: z.number(),
  sensors: z.array(WeatherLinkSensorDataSchema),
  generated_at: z.number(),
});

export type WeatherLinkHistoricResponse = z.infer<typeof WeatherLinkHistoricResponseSchema>;
