export type CanonicalUnit =
  | 'celsius'
  | 'hPa'
  | 'm/s'
  | 'mm'
  | 'mm/h'
  | 'W/m2'
  | 'degrees'
  | 'percent'
  | 'uv_index'
  | 'μg/m3'
  | 'volumetric';

export const MEASUREMENT_UNITS: Record<string, CanonicalUnit> = {
  'temperature.outdoor': 'celsius',
  'temperature.indoor': 'celsius',
  'temperature.apparent': 'celsius',
  'temperature.dewPoint': 'celsius',
  'temperature.heatIndex': 'celsius',
  'temperature.windChill': 'celsius',
  'temperature.wetBulb': 'celsius',
  'temperature.thwIndex': 'celsius',
  'temperature.thswIndex': 'celsius',
  'humidity.outdoor': 'percent',
  'humidity.indoor': 'percent',
  'pressure.seaLevel': 'hPa',
  'pressure.absolute': 'hPa',
  'pressure.trend': 'hPa',
  'wind.speed': 'm/s',
  'wind.gust': 'm/s',
  'wind.direction': 'degrees',
  'wind.speedAvg1Min': 'm/s',
  'wind.speedAvg2Min': 'm/s',
  'wind.speedAvg10Min': 'm/s',
  'rain.rate': 'mm/h',
  'rain.last15Min': 'mm',
  'rain.last60Min': 'mm',
  'rain.last24Hr': 'mm',
  'rain.daily': 'mm',
  'rain.monthly': 'mm',
  'rain.yearly': 'mm',
  'rain.stormTotal': 'mm',
  'solar.radiation': 'W/m2',
  'uv.index': 'uv_index',
  'air.pm1': 'μg/m3',
  'air.pm2_5': 'μg/m3',
  'air.pm10': 'μg/m3',
  'soil.temperature': 'celsius',
  'soil.moisture': 'volumetric',
  'leaf.wetness': 'volumetric',
  'evapotranspiration': 'mm',
};
