/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnualRouteImport } from './routes/annual'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TrendsRouteImport } from './routes/trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualRoute = AnnualRouteImport.update({
  id: '/annual',
  path: '/annual',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annual': typeof AnnualRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/outputs': typeof OutputsRoute
  '/records': typeof RecordsRoute
  '/system': typeof SystemRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annual': typeof AnnualRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/outputs': typeof OutputsRoute
  '/records': typeof RecordsRoute
  '/system': typeof SystemRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annual': typeof AnnualRoute
  '/compare': typeof CompareRoute
  '/downloads': typeof DownloadsRoute
  '/history': typeof HistoryRoute
  '/outputs': typeof OutputsRoute
  '/records': typeof RecordsRoute
  '/system': typeof SystemRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annual'
    | '/compare'
    | '/downloads'
    | '/history'
    | '/outputs'
    | '/records'
    | '/system'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annual'
    | '/compare'
    | '/downloads'
    | '/history'
    | '/outputs'
    | '/records'
    | '/system'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/annual'
    | '/compare'
    | '/downloads'
    | '/history'
    | '/outputs'
    | '/records'
    | '/system'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnualRoute: typeof AnnualRoute
  CompareRoute: typeof CompareRoute
  DownloadsRoute: typeof DownloadsRoute
  HistoryRoute: typeof HistoryRoute
  OutputsRoute: typeof OutputsRoute
  RecordsRoute: typeof RecordsRoute
  SystemRoute: typeof SystemRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual': {
      id: '/annual'
      path: '/annual'
      fullPath: '/annual'
      preLoaderRoute: typeof AnnualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnualRoute: AnnualRoute,
  CompareRoute: CompareRoute,
  DownloadsRoute: DownloadsRoute,
  HistoryRoute: HistoryRoute,
  OutputsRoute: OutputsRoute,
  RecordsRoute: RecordsRoute,
  SystemRoute: SystemRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
